### PR TITLE
Add 26100.560

### PR DESCRIPTION
**Pull request by admin-elvistrujanovic**
This build is missing here but it should be added since it's an part of RP channel too.

### CODE REVIEW

**Comment by admin-elvistrujanovic** [comment]
@bleblancMSFT Can you look at this case too? It seems that build is missing so could this build be added to the list too? Thanks!

**Comment by bleblancMSFT** [comment]
Build 26100.560 was not released to Release Preview and was only available as an ISO - we noted the ISO release on 5/22 for Build 26100 instead.

**Comment by admin-elvistrujanovic** [comment]
> @admin-elvistrujanovic Build 26100.560 was not released to Release Preview and was only available as an ISO - we noted the ISO release on 5/22 for Build 26100 instead.

But when an person install that build, it's flagged as release preview build already.... How could not be a part of release preview builds. It's like an older release of release preview that also have an ISO version too instead of 26100.712 that doesn't have ISO version.

**Comment by bleblancMSFT** [comment]
> > @admin-elvistrujanovic Build 26100.560 was not released to Release Preview and was only available as an ISO - we noted the ISO release on 5/22 for Build 26100 instead.
> 
> But when an person install that build, it's flagged as release preview build already.... How could not be a part of release preview builds. It's like an older release of release preview that also have an ISO version too and it's good for faster and better reinstallation of Windows to upgrade to Release Preview of 24H2 builds instead of 26100.712 that doesn't have an ISO version like 26100.560.

Build 26100.560 is just an ISO, it was never flighted to Release Preview or released there. Release Preview has Build 26100.712 and if someone installs using the ISO and lands on Build 26100.560, they will get Build 26100.712 offered. We're not considering the ISO a Release Preview flight. We won't be changing Flight Hub. Thanks for the feedback!

**Pull request closed without merging**
