### PR TITLE
fix misleading header to right part of article

### PR DESCRIPTION
**Pull request by jessyrod68**
Changed language and added link to right part of content.

### CODE REVIEW

**Comment by jessyrod68** [comment]
Manage Broken Link

The highlighted link leads to 404 page. Should lead to: https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-manage

**Comment by mypil** [comment]
@cdmm12 - can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@cdmm12 - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR?

**Pull request merged**
