### PR TITLE
Update Flight Hub to add latest Slow & Release Preview builds for the 19H2 section

### PR DESCRIPTION
**Pull request by ItzLevvie**
**This PR adds:**
* Added build **18362.10024** that went to the **Slow** ring.
* Added _missing_ build **18363.387** that went to the **Release Preview** ring.

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@lizap - PR is ready for final review. 

 Thank you.

cc: @kenwith

**Comment by ItzLevvie** [comment]
cc @lizap

**Comment by mypil** [comment]
adding @bleblancMSFT to the assignee as suggested by lizap to help review and merge this PR.

Thank you.

cc: @kenwith

**Comment by bleblancMSFT** [comment]
These updates have already been made in Flight Hub.

**Comment by ItzLevvie** [comment]
@bleblancMSFT You forgot to add build 18363.388

**Comment by bleblancMSFT** [comment]
@ItzLevvie I see it listed under 19H2 here on my end? Maybe I'm missing something?

**Comment by ItzLevvie** [comment]
@bleblancMSFT Ah sorry, I meant 18363.38**7**

**Comment by bleblancMSFT** [comment]
@ItzLevvie I didn't know 18363.387 went to RP? I was told it didn't.

**Comment by ItzLevvie** [comment]
@bleblancMSFT Seems like it did, according to: https://www.windowscentral.com/new-windows-10-fixes-issues-uninstalling-19h2-updates and on the blog post:
image

**Pull request merged**
