### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by hosseinmanafi**
URL 22000.176 is incorrectly referenced to 168.

### CODE REVIEW

**Comment by hosseinmanafi** [comment]
URL 22000.176 is incorrectly referenced to 168.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@bleblancMSFT Please merge this PR. Thanks

**Comment by riverar** [comment]
Was already fixed in https://github.com/MicrosoftDocs/windows-insider/commit/57d00b060517036344d5b2d2336dc915c2baaea6, this PR can be closed.

**Pull request closed without merging**
