### PR TITLE
Added 26100.712 build

### PR DESCRIPTION
**Pull request by admin-elvistrujanovic**
Added 26100.712 build and updated the table scheme to include RP (Release Preview) builds.

### CODE REVIEW

**Comment by admin-elvistrujanovic** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by admin-elvistrujanovic** [comment]
@bleblancMSFT Please, merge these changes to the public branch of this repository if everything looks fine to you. If more modifications needs to be done, please let me know and it will apply them as soon as possible. Thanks!

**Comment by bleblancMSFT** [comment]
I am closing this as we're making changes in our private repo to add the latest flights.

**Comment by admin-elvistrujanovic** [comment]
> We're making changes in our private repo to add the latest flights. 

If I understand you correctly, this also includes RP builds for 24H2 so no one needs to suggest those changes since it's already work-in-progress behind the screens

**Comment by admin-elvistrujanovic** [comment]
It's closed since RP scheme has been applied by staff

**Pull request closed without merging**
