### PR TITLE
the section on "Set up Insider Preview builds using Intune" is not up…

### PR DESCRIPTION
**Pull request by Sorevitnod**
… to date with the new Microsoft Endpoint Manager Update Center

the section on "Set up Insider Preview builds using Intune" is not up to date with the new Microsoft Endpoint Manager Update Center

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — COMMENTED** [review]
@yogkumgit - This is a request for the **Set up Insider Preview builds using Intune** section to be updated. I can only do a copy review once this section has been updated. Thanks.

**Comment by yogkumgit** [comment]
@v-allsh @bleblancMSFT @dougkim Please address this issue. Thanks

**Comment by yogkumgit** [comment]
@v-allsh @bleblancMSFT @dougkim Gentle reminder.

**Pull request closed without merging**
