### PR TITLE
Upgrade loc priority metadata value

### PR DESCRIPTION
**Pull request by TinaMcN**
Localized versions are getting very high page views, let's human translate this one.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@bleblancMSFT Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@riverar Please help.

**Comment by yogkumgit** [comment]
Gentle reminder @bleblancMSFT and @riverar

**Comment by riverar** [comment]
This documentation is just cut/paste from the English-only blog posts. I don't recommend any changes in terms of loc. I think Brandon also has major changes coming to this docset, further negating the need to bump loc priority.

Opinion: This PR can be closed.

**Pull request closed without merging**
