### PR TITLE
Update Flight Hub to include 19H2 builds

### PR DESCRIPTION
**Pull request by ItzLevvie**

### CODE REVIEW

**Comment by mypil** [comment]
@lizap - PR is ready for final review. Thank you.

**Comment by mypil** [comment]
This will also resolve issue #207

**Comment by DaniHalfin** [comment]
@bleblancMSFT - can you take a look? Thanks!

**Comment by lizap** [comment]
This content was updated in our private repo with a slightly different approach. You can see that change live here: https://docs.microsoft.com/en-us/windows-insider/flight-hub/#next-feature-update-for-windows-10-19h2

**Pull request closed without merging**
