### PR TITLE
Fix spelling mistakes, incorrect dates, and more

### PR DESCRIPTION
**Pull request by ItzLevvie**
***This PR adds the following***:

File: ```wip/flight-hub/index.md```:
* Changed 2/**12**/2020 to 2/**11**/2020 to match the date of when build **19041.84** was published to the Slow ring
* Changed 2/**25**/2020 to 2/**26**/2020 to match the date of when build **19041.84** was published to WSUS.
* Removed **en-us** locale from build **19041.84** ISO link

File: ```wip/at-home/Active-Dev-Branch-Beta.md```:
* Changed ```Developmemnt``` to ```Development```
* Changed ```RS_PRELEASE``` to ```RS_PRERELEASE```
* Added hyperlinks to Microsoft Design posts from Medium to match the blog post of build **19569**

File: ```wip/at-home/Whats-new-wip-at-home-1809.md```
* Added spaces between characters to make it more readable
* Changed keyboard shortcut from Ctrl + **B** to Ctrl + **E** to match the one shown in the image

File: ```wip/at-home/feedback.md```
* Removed unneeded space to match other bullet points

File: ```wip/at-home/whats-new-apps.md```
* Added bullet points to a content under the ```Phone screen now supports pen input``` sub-header, which is under the ```Your Phone``` header

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@bleblancMSFT - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

**Comment by bleblancMSFT** [comment]
There is one item we need to revert. The date for Build 19041.84 going to WSUS needs to reflect 2/26 which is the date we officially [made the announcement blog post](https://blogs.windows.com/windowsexperience/2020/02/26/releasing-windows-10-insider-preview-build-19041-84-to-wsus/) and not 2/25. This was something we did intentionally in Flight Hub to match the announcement.

**Comment by ItzLevvie** [comment]
@bleblancMSFT The changes look fine here: https://github.com/MicrosoftDocs/windows-insider/blob/656c0696a4cee83178d33fe20bc95e99680c9b92/wip/flight-hub/index.md#upcoming-windows-10-feature-update-20h1. Is there anything I'm missing?

**Comment by bleblancMSFT** [comment]
@ItzLevvie you are right, I mis-red! I merged this!

**Pull request merged**
