### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by jessyrod68**
current link leads to 404 page. this is the correct link

https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-manage

### CODE REVIEW

**Comment by mypil** [comment]
@cdmm12 - can you please assist to check, approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@cdmm12  - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR?

Thank you.

**Comment by mypil** [comment]
@kenwith - would you be able to merge the content of this PR? This is for a broken link. Thank you,

**Comment by cdmm12** [comment]
Quick update that the error was on the Eval Center side and has been fixed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
