### PR TITLE
Update Flight Hub to include latest 20H1 builds

### PR DESCRIPTION
**Pull request by ItzLevvie**
* Added missing SDK for build 18890
* Added build 18941 & 18945 to the list
* Added missing hyperlink for the ISO section for build 18912
* Fixed the date for SDK release of build 18917
* Fixed all SDK links (changed "buildingapps" to "windowsdeveloper")
* Removed "en-us" from ISO links

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@lizap - PR has been copy edited and is ready for final review.

Thank you.

**Comment by DaniHalfin** [comment]
@bleblancMSFT - can you take a look? Thanks!

**Comment by lizap** [comment]
Changes in this PR conflict with changes made internally. I believe we have the [right links and dates](https://docs.microsoft.com/en-us/windows-insider/flight-hub/#current-fast-ring-builds-of-windows-10-20h1). If there are other changes that we didn't catch, please submit them as a new PR. Thanks!

**Pull request closed without merging**
