### PR TITLE
updated latest fast build

### PR DESCRIPTION
**Pull request by AaronPinto**

### CODE REVIEW

**Comment by mypil** [comment]
@lizap - Can you please assist to check, approve and merge the content of this PR?

Thank you.

**Comment by mypil** [comment]
@lizap - We would like to follow up. Can you please assist to check, approve and merge the content of this PR?

Thank you.

**Comment by mypil** [comment]
@lizap @AndreaBarr - Would you be able to merge the content of this PR?

cc: @dougkim

**Comment by lizap** [comment]
Thanks for your contribution - we've updated the article in question with the same information. As such, and to avoid any conflicts, I'm going to close this PR without merging. Thanks!

**Pull request closed without merging**
